import type { BranchCode, LookupType, RoleKey } from '@csm/shared'

// Static seed data. Names, places and companies are Bengaluru-flavoured and fictional.

type L = { code: string; en: string; kn: string; parent?: string }

export const LOOKUPS: Record<LookupType, L[]> = {
  countries: [
    { code: 'IN', en: 'India', kn: 'ಭಾರತ' },
    { code: 'US', en: 'United States', kn: 'ಅಮೆರಿಕ ಸಂಯುಕ್ತ ಸಂಸ್ಥಾನ' },
    { code: 'GB', en: 'United Kingdom', kn: 'ಯುನೈಟೆಡ್ ಕಿಂಗ್‌ಡಮ್' },
    { code: 'AE', en: 'United Arab Emirates', kn: 'ಸಂಯುಕ್ತ ಅರಬ್ ಸಂಸ್ಥಾನ' },
    { code: 'SG', en: 'Singapore', kn: 'ಸಿಂಗಾಪುರ' },
    { code: 'LK', en: 'Sri Lanka', kn: 'ಶ್ರೀಲಂಕಾ' },
    { code: 'NP', en: 'Nepal', kn: 'ನೇಪಾಳ' },
    { code: 'AU', en: 'Australia', kn: 'ಆಸ್ಟ್ರೇಲಿಯಾ' },
    { code: 'CA', en: 'Canada', kn: 'ಕೆನಡಾ' },
  ],
  states: [
    { code: 'KA', en: 'Karnataka', kn: 'ಕರ್ನಾಟಕ' },
    { code: 'TN', en: 'Tamil Nadu', kn: 'ತಮಿಳುನಾಡು' },
    { code: 'KL', en: 'Kerala', kn: 'ಕೇರಳ' },
    { code: 'AP', en: 'Andhra Pradesh', kn: 'ಆಂಧ್ರ ಪ್ರದೇಶ' },
    { code: 'TS', en: 'Telangana', kn: 'ತೆಲಂಗಾಣ' },
    { code: 'MH', en: 'Maharashtra', kn: 'ಮಹಾರಾಷ್ಟ್ರ' },
    { code: 'GA', en: 'Goa', kn: 'ಗೋವಾ' },
  ],
  titles: [
    { code: 'mr', en: 'Mr', kn: 'ಶ್ರೀ' },
    { code: 'mrs', en: 'Mrs', kn: 'ಶ್ರೀಮತಿ' },
    { code: 'ms', en: 'Ms', kn: 'ಕುಮಾರಿ' },
    { code: 'dr', en: 'Dr', kn: 'ಡಾ.' },
  ],
  occupations: [
    { code: 'salaried_private', en: 'Salaried — private sector', kn: 'ವೇತನದಾರ — ಖಾಸಗಿ ವಲಯ' },
    { code: 'salaried_govt', en: 'Salaried — government', kn: 'ವೇತನದಾರ — ಸರ್ಕಾರಿ' },
    { code: 'self_employed', en: 'Self-employed professional', kn: 'ಸ್ವಉದ್ಯೋಗಿ ವೃತ್ತಿಪರ' },
    { code: 'business', en: 'Business owner', kn: 'ಉದ್ಯಮಿ' },
    { code: 'student', en: 'Student', kn: 'ವಿದ್ಯಾರ್ಥಿ' },
    { code: 'homemaker', en: 'Homemaker', kn: 'ಗೃಹಿಣಿ' },
    { code: 'retired', en: 'Retired', kn: 'ನಿವೃತ್ತ' },
    { code: 'agriculture', en: 'Agriculture', kn: 'ಕೃಷಿ' },
  ],
  products: [
    { code: 'savings', en: 'Savings account', kn: 'ಉಳಿತಾಯ ಖಾತೆ' },
    { code: 'current', en: 'Current account', kn: 'ಚಾಲ್ತಿ ಖಾತೆ' },
    { code: 'credit_card', en: 'Credit card', kn: 'ಕ್ರೆಡಿಟ್ ಕಾರ್ಡ್' },
    { code: 'personal_loan', en: 'Personal loan', kn: 'ವೈಯಕ್ತಿಕ ಸಾಲ' },
    { code: 'home_loan', en: 'Home loan', kn: 'ಗೃಹ ಸಾಲ' },
    { code: 'fixed_deposit', en: 'Fixed deposit', kn: 'ನಿಶ್ಚಿತ ಠೇವಣಿ' },
    { code: 'remittance', en: 'Remittance', kn: 'ಹಣ ರವಾನೆ' },
  ],
  srCategories: [
    { code: 'cards', en: 'Card services', kn: 'ಕಾರ್ಡ್ ಸೇವೆಗಳು' },
    { code: 'accounts', en: 'Account services', kn: 'ಖಾತೆ ಸೇವೆಗಳು' },
    { code: 'kyc', en: 'KYC & profile', kn: 'KYC ಮತ್ತು ಪ್ರೊಫೈಲ್' },
    { code: 'digital', en: 'Digital banking', kn: 'ಡಿಜಿಟಲ್ ಬ್ಯಾಂಕಿಂಗ್' },
    { code: 'loans', en: 'Loans', kn: 'ಸಾಲಗಳು' },
    { code: 'complaints', en: 'Complaints', kn: 'ದೂರುಗಳು' },
  ],
  srSubCategories: [
    { parent: 'cards', code: 'card_blocked', en: 'Card blocked', kn: 'ಕಾರ್ಡ್ ನಿರ್ಬಂಧಿಸಲಾಗಿದೆ' },
    { parent: 'cards', code: 'card_replacement', en: 'Replace damaged card', kn: 'ಹಾಳಾದ ಕಾರ್ಡ್ ಬದಲಾವಣೆ' },
    { parent: 'cards', code: 'limit_change', en: 'Change card limit', kn: 'ಕಾರ್ಡ್ ಮಿತಿ ಬದಲಾವಣೆ' },
    { parent: 'cards', code: 'pin_reset', en: 'Reset card PIN', kn: 'ಕಾರ್ಡ್ PIN ಮರುಹೊಂದಿಕೆ' },
    { parent: 'accounts', code: 'statement', en: 'Account statement', kn: 'ಖಾತೆ ವಿವರಣಾ ಪತ್ರ' },
    { parent: 'accounts', code: 'cheque_book', en: 'Cheque book request', kn: 'ಚೆಕ್ ಪುಸ್ತಕ ವಿನಂತಿ' },
    { parent: 'accounts', code: 'passbook', en: 'Passbook reissue', kn: 'ಪಾಸ್‌ಬುಕ್ ಮರುವಿತರಣೆ' },
    { parent: 'accounts', code: 'interest_cert', en: 'Interest certificate', kn: 'ಬಡ್ಡಿ ಪ್ರಮಾಣಪತ್ರ' },
    {
      parent: 'accounts',
      code: 'standing_order',
      en: 'Standing instruction issue',
      kn: 'ಸ್ಥಾಯಿ ಸೂಚನೆ ಸಮಸ್ಯೆ',
    },
    { parent: 'kyc', code: 'address_change', en: 'Change of address', kn: 'ವಿಳಾಸ ಬದಲಾವಣೆ' },
    { parent: 'kyc', code: 'name_change', en: 'Change of name', kn: 'ಹೆಸರು ಬದಲಾವಣೆ' },
    { parent: 'kyc', code: 'mobile_update', en: 'Update mobile number', kn: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನವೀಕರಣ' },
    { parent: 'kyc', code: 'joint_holder', en: 'Joint holder update', kn: 'ಜಂಟಿ ಖಾತೆದಾರರ ನವೀಕರಣ' },
    { parent: 'kyc', code: 'rekyc', en: 'Periodic re-KYC', kn: 'ಆವರ್ತಕ ಮರು-KYC' },
    {
      parent: 'digital',
      code: 'mb_pin',
      en: 'Mobile banking PIN reset',
      kn: 'ಮೊಬೈಲ್ ಬ್ಯಾಂಕಿಂಗ್ PIN ಮರುಹೊಂದಿಕೆ',
    },
    { parent: 'digital', code: 'upi_failed', en: 'UPI payment failed', kn: 'UPI ಪಾವತಿ ವಿಫಲ' },
    {
      parent: 'digital',
      code: 'netbanking_lock',
      en: 'Net banking locked',
      kn: 'ನೆಟ್ ಬ್ಯಾಂಕಿಂಗ್ ಲಾಕ್ ಆಗಿದೆ',
    },
    { parent: 'loans', code: 'foreclosure', en: 'Loan foreclosure', kn: 'ಸಾಲ ಮುಂಚಿತ ಮುಕ್ತಾಯ' },
    { parent: 'loans', code: 'emi_change', en: 'EMI date change', kn: 'EMI ದಿನಾಂಕ ಬದಲಾವಣೆ' },
    { parent: 'loans', code: 'noc', en: 'No-objection certificate', kn: 'ನಿರಾಕ್ಷೇಪಣಾ ಪ್ರಮಾಣಪತ್ರ' },
    {
      parent: 'complaints',
      code: 'atm_dispute',
      en: 'Disputed ATM withdrawal',
      kn: 'ವಿವಾದಿತ ATM ಹಿಂಪಡೆಯುವಿಕೆ',
    },
    { parent: 'complaints', code: 'wrong_charge', en: 'Incorrect charges', kn: 'ತಪ್ಪಾದ ಶುಲ್ಕಗಳು' },
    { parent: 'complaints', code: 'service', en: 'Service quality', kn: 'ಸೇವಾ ಗುಣಮಟ್ಟ' },
  ],
  blockReasons: [
    { code: 'suspected_fraud', en: 'Suspected fraud', kn: 'ಶಂಕಿತ ವಂಚನೆ' },
    { code: 'court_order', en: 'Court or regulator order', kn: 'ನ್ಯಾಯಾಲಯ ಅಥವಾ ನಿಯಂತ್ರಕ ಆದೇಶ' },
    { code: 'kyc_expired', en: 'KYC expired', kn: 'KYC ಅವಧಿ ಮುಗಿದಿದೆ' },
    { code: 'customer_request', en: 'Customer request', kn: 'ಗ್ರಾಹಕರ ವಿನಂತಿ' },
    { code: 'deceased', en: 'Customer deceased', kn: 'ಗ್ರಾಹಕರು ನಿಧನರಾಗಿದ್ದಾರೆ' },
  ],
}

export interface SeedStaff {
  staffId: string
  name: string
  roleKey: RoleKey
  branchCode: BranchCode
  status?: 'active' | 'deactivated'
  overrides?: { screenKey: string; grant: ('export' | 'approve')[]; revoke: ('export' | 'approve')[] }[]
}

export const STAFF: SeedStaff[] = [
  { staffId: 'admin001', name: 'Raghavendra Rao', roleKey: 'admin', branchCode: '0001' },
  { staffId: 'sup001', name: 'Naveen Gowda', roleKey: 'supervisor', branchCode: '0001' },
  { staffId: 'sup002', name: 'Sowmya Murthy', roleKey: 'supervisor', branchCode: '0004' },
  { staffId: 'sup003', name: 'Prasanna Kamath', roleKey: 'supervisor', branchCode: '0007' },
  {
    staffId: 'csr001',
    name: 'Kavya Hegde',
    roleKey: 'csr',
    branchCode: '0001',
    // Matches the Users & access mockup: one per-user grant on top of the role.
    overrides: [{ screenKey: 'customers.search', grant: ['export'], revoke: [] }],
  },
  { staffId: 'csr002', name: 'Arun Shetty', roleKey: 'csr', branchCode: '0004' },
  { staffId: 'csr003', name: 'Harish Kumar', roleKey: 'csr', branchCode: '0007' },
  { staffId: 'csr004', name: 'Deepa Bhat', roleKey: 'csr', branchCode: '0007', status: 'deactivated' },
]

/** Known password for practice (`npm run seed -- --demo`). Never used unless asked for. */
export const DEMO_PASSWORD = 'Namma-Bengaluru-2026'

export const FEMALE_NAMES = [
  'Ananya',
  'Kavya',
  'Shreya',
  'Meghana',
  'Pooja',
  'Lakshmi',
  'Deepa',
  'Sowmya',
  'Divya',
  'Bhavya',
  'Sahana',
  'Spoorthi',
  'Rashmi',
  'Nandini',
  'Pallavi',
  'Shruthi',
  'Aishwarya',
  'Keerthana',
  'Vidya',
  'Harini',
  'Chaitra',
  'Ramya',
  'Sneha',
  'Anusha',
  'Varsha',
  'Akshatha',
  'Sindhu',
  'Tejaswini',
  'Yashaswini',
  'Radhika',
]
export const MALE_NAMES = [
  'Kiran',
  'Vikram',
  'Manjunath',
  'Suresh',
  'Prakash',
  'Naveen',
  'Raghavendra',
  'Arun',
  'Harish',
  'Rakesh',
  'Mahesh',
  'Ganesh',
  'Santosh',
  'Shashank',
  'Pradeep',
  'Sudeep',
  'Chethan',
  'Darshan',
  'Abhishek',
  'Karthik',
  'Nikhil',
  'Puneeth',
  'Rohan',
  'Sachin',
  'Srinivas',
  'Venkatesh',
  'Anand',
  'Ananth',
  'Girish',
  'Yogesh',
]
export const SURNAMES = [
  'Rao',
  'Gowda',
  'Hegde',
  'Shetty',
  'Reddy',
  'Bhat',
  'Nayak',
  'Kulkarni',
  'Shivakumar',
  'Narayan',
  'Murthy',
  'Kumar',
  'Iyengar',
  'Acharya',
  'Kamath',
  'Pai',
  'Shenoy',
  'Prabhu',
  'Naik',
  'Desai',
  'Patil',
  'Swamy',
  'Raju',
  'Krishna',
  'Prasad',
  'Hiremath',
  'Joshi',
  'Urs',
  'Poojary',
  'Karanth',
]

export const LOCALITIES: [string, string][] = [
  ['Koramangala', '560034'],
  ['Indiranagar', '560038'],
  ['Jayanagar', '560041'],
  ['JP Nagar', '560078'],
  ['HSR Layout', '560102'],
  ['Whitefield', '560066'],
  ['Malleshwaram', '560003'],
  ['Rajajinagar', '560010'],
  ['Basavanagudi', '560004'],
  ['BTM Layout', '560076'],
  ['Electronic City', '560100'],
  ['Hebbal', '560024'],
  ['Yelahanka', '560064'],
  ['Banashankari', '560050'],
  ['Marathahalli', '560037'],
  ['Bellandur', '560103'],
  ['RT Nagar', '560032'],
  ['Vijayanagar', '560040'],
  ['Sadashivanagar', '560080'],
  ['Frazer Town', '560005'],
]

export const EMPLOYERS = [
  'Kaveri Software Labs Pvt Ltd',
  'Nandi Hills Logistics Pvt Ltd',
  'Malnad Coffee Traders',
  'Tunga Textiles',
  'Hampi Infra Projects Ltd',
  'Sahyadri Health Services',
  'Vidhana Consulting LLP',
  'Cubbon Analytics Pvt Ltd',
  'Lalbagh Foods Pvt Ltd',
  'Garuda Aerospace Components',
  'Sharavathi Power Systems',
  'Mysore Silk Exports',
]

export const MOBILE_PREFIXES = [
  '98450',
  '99011',
  '97399',
  '96860',
  '98868',
  '99862',
  '94480',
  '90080',
  '98440',
  '97422',
  '99000',
  '94483',
  '80950',
  '70220',
  '63600',
]

export const SR_SUBJECTS: Record<string, string[]> = {
  card_blocked: ['Card blocked after lost wallet', 'Debit card blocked after wrong PIN attempts'],
  card_replacement: ['Replace damaged card', 'Card chip not working at POS'],
  limit_change: ['Increase credit card limit', 'Reduce ATM withdrawal limit'],
  pin_reset: ['Forgot debit card PIN', 'Generate new card PIN'],
  statement: ['Statement for visa application', 'Six-month statement for home loan'],
  cheque_book: ['Cheque book request', 'Cheque book not received'],
  passbook: ['Lost passbook — reissue', 'Passbook pages full'],
  interest_cert: ['Interest certificate FY 2025–26', 'TDS certificate for fixed deposit'],
  standing_order: ['Standing order not executed', 'Cancel standing instruction for SIP'],
  address_change: ['Update address after move to HSR Layout', 'New address in Whitefield'],
  name_change: ['Change of name after marriage', 'Correct spelling of surname'],
  mobile_update: ['Update registered mobile number', 'OTP going to old mobile number'],
  joint_holder: ['Joint account holder update', 'Add spouse as joint holder'],
  rekyc: ['Periodic re-KYC due', 'Re-KYC documents submitted at branch'],
  mb_pin: ['Reset mobile banking PIN', 'Mobile banking locked after app update'],
  upi_failed: ['UPI payment debited but not credited', 'UPI transfer failed twice'],
  netbanking_lock: ['Net banking locked', 'Net banking password expired'],
  foreclosure: ['Personal loan foreclosure quote', 'Close home loan early'],
  emi_change: ['Move EMI date to the 5th', 'EMI debited twice this month'],
  noc: ['NOC after vehicle loan closure', 'NOC for home loan closure'],
  atm_dispute: ['Disputed ATM withdrawal', 'Cash not dispensed at ATM'],
  wrong_charge: ['Incorrect minimum balance charge', 'SMS charges applied twice'],
  service: ['Long wait at branch counter', 'Call centre did not call back'],
}

export const COMMENTS = [
  'Called the customer and confirmed the details.',
  'Documents received at the branch.',
  'Forwarded to the cards team for action.',
  'Customer asked for an update by SMS.',
  'Waiting for the back office to confirm.',
  'Checked the transaction trail; no debit after the block.',
  'Customer will visit the branch on Saturday.',
  'Replacement dispatched by courier.',
]
